name: Prod

on:
  push:
    branches:
      - "main"

env:
  SSH_KEY_FILE_NAME: private.pem
  APP_DIR: hypefit-frontend

jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Extract the environment variable
        run: echo "${{ secrets.PROD_ENV_VARS }}" > .env
      - name: Install pnpm
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm build
      - name: Store SSH key
        run: echo "${{ secrets.PROD_SSH_KEY_CONTENT }}" > ${{ env.SSH_KEY_FILE_NAME }}
      - name: Change SSH key permission
        run: chmod 0400 ${{ env.SSH_KEY_FILE_NAME }}
      - name: Copy file to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SSH_USERNAME }}
          port: ${{ secrets.PROD_SSH_PORT }}
          key_path: ${{ env.SSH_KEY_FILE_NAME }}
          source: "./build,ecosystem.config.cjs,package.json"
          target: "/home/${{ secrets.PROD_SSH_USERNAME }}/from-actions/${{ env.APP_DIR }}"
      - name: Executing remote command using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SERVER_IP }}
          username: ${{ secrets.PROD_SSH_USERNAME }}
          key_path: ${{ env.SSH_KEY_FILE_NAME }}
          port: ${{ secrets.PROD_SSH_PORT }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            source ~/.profile
            mkdir -p /home/${{ secrets.PROD_SSH_USERNAME }}/${{ env.APP_DIR }}
            cd /home/${{ secrets.PROD_SSH_USERNAME }}/${{ env.APP_DIR }}
            rm -rf *
            mv ../from-actions/${{ env.APP_DIR }}/* .
            pm2 reload ecosystem.config.cjs
            pm2 save
